name: flutter_integration_material_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  simple_animations: ^4.0.0
  shared_preferences: ^2.0.8
  http: ^0.13.3
  barcode_widget: ^2.0.1
  url_launcher: ^6.0.12
  giffy_dialog: ^1.8.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family : Heart
      fonts:
        - asset: assets/font/HaveHeartOne.ttf
          weight: 500
    - family : Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family : Berlin
      fonts:
        - asset: assets/font/berlin.TTF
          weight: 600
    - family: Popins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
    - family : Amira
      fonts:
        - asset: assets/font/Amira.otf
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600
    - family : Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300

  # To addlib/Screen/UI_Screen/Plane_Apps/Assets to your application, add anlib/Screen/UI_Screen/Plane_Apps/Assets section, like this:
  assets:
    - assets/credentials.json
    - assets/map_style.txt
    - assets/images/marker.png
    - assets/pdf/sample.pdf
    - assets/illustration/error_illustration/error1.jpg
    - assets/illustration/error_illustration/error2.jpg
    - assets/illustration/error_illustration/error3.jpg
    - assets/illustration/error_illustration/error3.jpg
    - assets/illustration/error_illustration/error4.jpg
    - assets/illustration/error_illustration/error5.jpg
    - assets/illustration/error_illustration/error6.jpg
    - assets/illustration/error_illustration/error7.jpg
    - assets/illustration/error_illustration/error8.jpg
    - assets/illustration/error_illustration/error9.jpg
    - assets/illustration/error_illustration/error10.jpg
    - assets/illustration/error_illustration/error11.jpg
    - assets/illustration/error_illustration/error12.jpg
    - assets/illustration/error_illustration/error13.jpg
    - assets/illustration/error_illustration/error14.jpg
    - assets/illustration/error_illustration/error15.jpg
    - assets/illustration/error_illustration/error16.jpg
    - assets/illustration/error_illustration/error17.jpg
    - assets/illustration/error_illustration/error18.jpg
    - assets/illustration/error_illustration/error19.jpg
    - assets/illustration/error_illustration/error20.jpg
    - assets/illustration/error_illustration/error21.jpg
    - assets/illustration/error_illustration/error22.jpg
    - assets/illustration/error_illustration/error23.jpg
    - assets/illustration/error_illustration/error24.jpg
    - assets/illustration/error_illustration/error25.jpg
    - assets/illustration/error_illustration/error26.jpg
    - assets/illustration/error_illustration/error27.jpg
    - assets/illustration/error_illustration/error28.jpg
    - assets/illustration/error_illustration/error29.jpg
    - assets/illustration/error_illustration/error30.jpg
    - assets/illustration/error_illustration/error31.jpg
    - assets/illustration/error_illustration/error32.jpg
    - assets/illustration/error_illustration/error33.jpg
    - assets/illustration/error_illustration/error34.jpg
    - assets/illustration/error_illustration/error35.jpg
    - assets/illustration/error_illustration/error36.jpg
    - assets/illustration/error_illustration/error37.jpg
    - assets/illustration/error_illustration/error38.jpg
    - assets/illustration/error_illustration/error39.jpg
    - assets/illustration/error_illustration/error40.jpg
    - assets/illustration/error_illustration/error40.jpg
    - assets/illustration/SplashScreen_illustration/Splash1.jpg
    - assets/illustration/SplashScreen_illustration/Splash2.jpg
    - assets/illustration/SplashScreen_illustration/Splash3.jpg
    - assets/illustration/SplashScreen_illustration/Splash4.jpg
    - assets/illustration/SplashScreen_illustration/Splash5.jpg
    - assets/illustration/SplashScreen_illustration/Splash6.jpg
    - assets/illustration/SplashScreen_illustration/Splash7.jpg
    - assets/images/boarding1.png
    - assets/images/boarding2.png
    - assets/images/boarding3.png
    - assets/images/board1.png
    - assets/images/board2.png
    - assets/images/board3.png
    - assets/images/onBoarding1.gif
    - assets/images/onBoarding2.gif
    - assets/images/onBoarding3.gif
    - assets/images/onBoardingC1.png
    - assets/images/onBoardingC2.png
    - assets/images/onBoardingC3.png
    - assets/images/SplashScreen.png
    - assets/images/help.png
    - assets/images/screenCard.png
    - assets/images/materialIcon.png
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/logo.png
    - assets/integration/language_integration/
    - lib/Screen/Integration/Language_Integration/language/ar-DZ.json
    - lib/Screen/Integration/Language_Integration/language/en-US.json
    - lib/Screen/Integration/Language_Integration/language/zh-CN.json
    - lib/Screen/Integration/Language_Integration/language/pt-BR.json
    - lib/Screen/Integration/Language_Integration/language/hi-IN.json
    - lib/Screen/Integration/Language_Integration/language/id-ID.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
